name: PR api-service

on:
  pull_request:
    branches:
      - main
  
env:
  PROJECT_ID: rtw-armory
  REGION: europe-north1
  GAR_LOCATION: europe-north1-docker.pkg.dev/rtw-armory/rtw-armory-artifact-registry-prod
  DOCKERFILE_LOCATION: packages/api-service/Dockerfile
  GKE_CLUSTER: rtw-armory
  GKE_ZONE: europe-north1-b
  NODE_ENV: production

jobs:
  pr-api:
    runs-on: ubuntu-latest
    steps:
      - name: "Checkout"
        uses: "actions/checkout@v3"

      - name:
        run: 'echo "$SSH_KEY" > packages/api-service/keys/gcp-sa.json'
        shell: bash
        env:
          SSH_KEY: ${{ secrets.GCP_BUCKET_SA }}

      - id: "auth"
        uses: "google-github-actions/auth@v1"
        with:
          credentials_json: "${{ secrets.SERVICE_ACCOUNT_KEY }}"

      - name: "Set up Cloud SDK"
        uses: "google-github-actions/setup-gcloud@v1"

      - name: "Use gcloud CLI"
        run: "gcloud info"

      - name: "Docker auth"
        run: |-
          gcloud auth configure-docker ${{ env.REGION }}-docker.pkg.dev --quiet

      - name: Build image
        run: |-
          docker build . -t ${{ env.GAR_LOCATION }}/api-service:$(git rev-parse --short HEAD) -f ${{ env.DOCKERFILE_LOCATION }}
          docker build . -t ${{ env.GAR_LOCATION }}/api-service:latest -f ${{ env.DOCKERFILE_LOCATION }}
