name: PR webapp

on:
  pull_request:
    branches:
      - main

env:
  PROJECT_ID: rtw-armory
  REGION: europe-north1
  GAR_LOCATION: europe-north1-docker.pkg.dev/rtw-armory/rtw-armory-artifact-registry-prod
  DOCKERFILE_LOCATION: packages/webapp/Dockerfile
  GKE_CLUSTER: rtw-armory
  GKE_ZONE: europe-north1-b
  NODE_ENV: production

jobs:
  pr-webapp:
    runs-on: ubuntu-latest
    steps:
      - name: "Checkout"
        uses: "actions/checkout@v3"

      - id: "auth"
        uses: "google-github-actions/auth@v1"
        with:
          credentials_json: "${{ secrets.SERVICE_ACCOUNT_KEY }}"

      - name: "Set up Cloud SDK"
        uses: "google-github-actions/setup-gcloud@v1"

      - name: "Use gcloud CLI"
        run: "gcloud info"

      - name: "Docker auth"
        run: |-
          gcloud auth configure-docker ${{ env.REGION }}-docker.pkg.dev --quiet

      - name: "copy"
        run: |-
          touch packages/webapp/.env.local
          echo "NEXT_PUBLIC_API_DESTINATION=http://34.88.65.99:8000/:path*" >> packages/webapp/.env.local
          echo "NEXT_BUILD_ID=2" >> packages/webapp/.env.local
          echo "BUILD_ID=2" >> packages/webapp/.env.local
      - name: Build image
        run: |-
          docker build . -t ${{ env.GAR_LOCATION }}/webapp:$(git rev-parse --short HEAD) -f ${{ env.DOCKERFILE_LOCATION }}
          docker build . -t ${{ env.GAR_LOCATION }}/webapp:latest -f ${{ env.DOCKERFILE_LOCATION }}
